using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace WPTweaker
{
    class EmulatorData
    {
#if !ARM
        public static List<string> SoundFiles = new List<string>()
        {
            "1_VZW_Airwaves.wma", "2_VZW_ Cube.wma", "AchievementNotifyPopup.wav", "Ahh Glitch.wma", "Alarm-01.wma", "Alarm-02.wma", 
            "Alarm-03.wma", "Alarm-04.wma", "Alarm-05.wma", "Alarm-06.wma", "Alert-01.wma", "Alert-02.wma", "Alert-03.wma", "Alert-04.wma", 
            "Alert-05.wma", "Alert-06.wma", "Alert-07.wma", "Alert-08.wma", "Alert-09.wma", "Alert-10.wma", "Alert_calendar.wma", "Alert_charging.wma", 
            "Alert_find_phone.wma", "Alert_low_battery.wma", "Alert_nudge.wma", "Applebite.wma", "Bird Box.wma", "Bouncey Bounce.wma", "Brikabrak.wma", 
            "Brimful.wma", "Broken Tone.wma", "Busy.wav", "BusyCDMA.wav", "BusyCDMA_Nokia.wav", "Busy_Nokia.wav", "Calldrop.wav", "Calldrop_Nokia.wav", 
            "Callwait.wav", "Callwait_Nokia.wav", "Cat.wma", "Chipper.wma", "Circles.wma", "CMAS.wma", "Congestion.wav", "Congestion_Nokia.wav", 
            "CopyPaste.wav", "Default.wav", "Dewdrop.wma", "Digital Thump.wma", "Disconnct.wav", "dtmf0.wav", "dtmf1.wav", "dtmf2.wav", "dtmf3.wav", 
            "dtmf4.wav", "dtmf5.wav", "dtmf6.wav", "dtmf7.wav", "dtmf8.wav", "dtmf9.wav", "dtmfast.wav", "dtmfpd.wav", "Earl's Torch.wma", 
            "Good Times.wma", "HWandSW.wav", "ImeAddToDictionary.wav", "ImeBluebirdOOV.wav", "ImeSelectCandidate.wav", "InCallBuzz.wma", 
            "Just Ice.wma", "KbdAccentPicker.wav", "KbdFunction.wav", "KbdKeyTap.wav", "KbdSpacebar.wav", "lock.wav", "Lucky Five.wma", 
            "Macro.wma", "Marbles.wma", "Miniature of Troy.wma", "Moanday.wma", "NfcInRange.wma", "NfcPaymentFail.wma", "NfcPaymentSuccess.wma", 
            "NfcTransactionComplete.wma", "Nokia calendar.wma", "Nokia clock.wma", "Nokia email.wma", "Nokia message.wma", "Nokia Tune Remix.wma", 
            "Nokia Tune.wma", "Nostalgia.wma", "Pinball.wma", "PingRing.wav", "Pip.wav", "Pool.wma", "Remind.wma", "Reorder.wav", "Reorder_Nokia.wav", 
            "Ring01.wma", "Ring02.wma", "Ring03.wma", "Ring04.wma", "Ring05.wma", "Ring06.wma", "Ring07.wma", "Ring08.wma", "Ring09.wma", "Ring10.wma", 
            "Ring11.wma", "Ring12.wma", "Ring13.wma", "Ring14.wma", "Ring15.wma", "Ring16.wma", "Ring17.wma", "Ring18.wma", "Ring19.wma", "Ring20.wma", 
            "Ring21.wma", "ringback.wav", "Ruby.wma", "Skate.wma", "Slow Coffee.wma", "Standard.wav", "Sweets.wma", "unlock.wav", "Voiceprvcy.wav", 
            "Warped.wma", "WiFiConnected.wav", "WiFiDisconnected.wav"
        };


        public static Dictionary<string, string> NotificationEventValues = new Dictionary<string, string>()
        {
            { "Achievement", @"C:\Programs\CommonFiles\Sounds\AchievementNotifyPopup.wav" },
            { "Alarm", @"C:\Programs\CommonFiles\Sounds\Alarm-01.wma" },
            { "BatteryCharging", @"C:\Programs\CommonFiles\Sounds\Alert_charging.wma" },
            { "BusyCDMA", @"C:\Programs\CommonFiles\Sounds\BusyCDMA_Nokia.wav" },
            { "BusyTone", @"C:\Programs\CommonFiles\Sounds\Busy_Nokia.wav" },
            { "CallDrop", @"C:\Programs\CommonFiles\Sounds\Calldrop_Nokia.wav" },
            { "CallWaiting", @"C:\Programs\CommonFiles\Sounds\Callwait_Nokia.wav" },
            { "Camera", @"" },
            { "CellBroadcast", @"C:\Programs\CommonFiles\Sounds\Remind.wma" },
            { "Clock", @"C:\Programs\CommonFiles\Sounds\Alarm-01.wma" },
            { "CMAS", @"C:\Programs\CommonFiles\Sounds\CMAS.wma" },
            { "Congestion", @"C:\Programs\CommonFiles\Sounds\Congestion_Nokia.wav" },
            { "CopyPaste", @"C:\Programs\CommonFiles\Sounds\CopyPaste.wav" },
            { "DownloadComplete", @"*none*" },
            { "Dtmf#", @"C:\Programs\CommonFiles\Sounds\Dtmfpd.wav" },
            { "Dtmf*", @"C:\Programs\CommonFiles\Sounds\Dtmfast.wav" },
            { "Dtmf0", @"C:\Programs\CommonFiles\Sounds\Dtmf0.wav" },
            { "Dtmf1", @"C:\Programs\CommonFiles\Sounds\Dtmf1.wav" },
            { "Dtmf2", @"C:\Programs\CommonFiles\Sounds\Dtmf2.wav" },
            { "Dtmf3", @"C:\Programs\CommonFiles\Sounds\Dtmf3.wav" },
            { "Dtmf4", @"C:\Programs\CommonFiles\Sounds\Dtmf4.wav" },
            { "Dtmf5", @"C:\Programs\CommonFiles\Sounds\Dtmf5.wav" },
            { "Dtmf6", @"C:\Programs\CommonFiles\Sounds\Dtmf6.wav" },
            { "Dtmf7", @"C:\Programs\CommonFiles\Sounds\Dtmf7.wav" },
            { "Dtmf8", @"C:\Programs\CommonFiles\Sounds\Dtmf8.wav" },
            { "Dtmf9", @"C:\Programs\CommonFiles\Sounds\Dtmf9.wav" },
            { "E-mail", @"C:\Programs\CommonFiles\Sounds\Alert-08.wma" },
            { "FindPhone", @"C:\Programs\CommonFiles\Sounds\Alert_find_phone.wma" },
            { "IM", @"C:\Programs\CommonFiles\Sounds\Alert-10.wma" },
            { "ImeAddToDictionary", @"ImeAddToDictionary.wav" },
            { "ImeBluebirdOOV", @"ImeBluebirdOOV.wav" },
            { "ImeSelectCandidate", @"ImeSelectCandidate.wav" },
            { "InCallBuzz", @"C:\Programs\CommonFiles\Sounds\InCallBuzz.wma" },
            { "InCallDtmf#", @"C:\Programs\CommonFiles\Sounds\Dtmfpd.wav" },
            { "InCallDtmf*", @"C:\Programs\CommonFiles\Sounds\Dtmfast.wav" },
            { "InCallDtmf0", @"C:\Programs\CommonFiles\Sounds\Dtmf0.wav" },
            { "InCallDtmf1", @"C:\Programs\CommonFiles\Sounds\Dtmf1.wav" },
            { "InCallDtmf2", @"C:\Programs\CommonFiles\Sounds\Dtmf2.wav" },
            { "InCallDtmf3", @"C:\Programs\CommonFiles\Sounds\Dtmf3.wav" },
            { "InCallDtmf4", @"C:\Programs\CommonFiles\Sounds\Dtmf4.wav" },
            { "InCallDtmf5", @"C:\Programs\CommonFiles\Sounds\Dtmf5.wav" },
            { "InCallDtmf6", @"C:\Programs\CommonFiles\Sounds\Dtmf6.wav" },
            { "InCallDtmf7", @"C:\Programs\CommonFiles\Sounds\Dtmf7.wav" },
            { "InCallDtmf8", @"C:\Programs\CommonFiles\Sounds\Dtmf8.wav" },
            { "InCallDtmf9", @"C:\Programs\CommonFiles\Sounds\Dtmf9.wav" },
            { "InCallVoiceText", @"C:\Programs\CommonFiles\Sounds\Callwait.wav" },
            { "Infbeg", @"C:\Programs\CommonFiles\Sounds\Remind.wma" },
            { "Infend", @"C:\Programs\CommonFiles\Sounds\Remind.wma" },
            { "InfInt", @"C:\Programs\CommonFiles\Sounds\Remind.wma" },
            { "Interrupt", @"C:\Programs\CommonFiles\Sounds\Remind.wma" },
            { "Keypress", @"C:\Programs\CommonFiles\Sounds\HWandSW.wav" },
            { "KnownCallerRing0", @"" },
            { "LoudestInCallVolume", @"" },
            { "Lowbattery", @"C:\Programs\CommonFiles\Sounds\Alert_low_battery.wma" },
            { "Mail", @"C:\Programs\CommonFiles\Sounds\Alert-08.wma" },
            { "Netbegin", @"C:\Programs\CommonFiles\Sounds\Remind.wma" },
            { "Netend", @"C:\Programs\CommonFiles\Sounds\Remind.wma" },
            { "NetInt", @"C:\Programs\CommonFiles\Sounds\Remind.wma" },
            { "NetworkDrop", @"C:\Programs\CommonFiles\Sounds\Calldrop_Nokia.wav" },
            { "NfcInRange", @"C:\Programs\CommonFiles\Sounds\NfcInRange.wma" },
            { "NfcPaymentFail", @"C:\Programs\CommonFiles\Sounds\NfcPaymentFail.wma" },
            { "NfcPaymentSuccess", @"C:\Programs\CommonFiles\Sounds\NfcPaymentSuccess.wma" },
            { "NfcTransactionComplete", @"C:\Programs\CommonFiles\Sounds\NfcTransactionComplete.wma" },
            { "NfcTransactionCompleteShort", @"C:\Programs\CommonFiles\Sounds\NfcTransactionComplete.wma" },
            { "Notification", @"C:\Programs\CommonFiles\Sounds\default.wav" },
            { "NotificationToast", @"C:\Programs\CommonFiles\Sounds\Alert-05.wma" },
            { "Password", @"*none*" },
            { "PhoneLocked", @"C:\Programs\CommonFiles\Sounds\lock.wav" },
            { "PhoneUnlocked", @"C:\Programs\CommonFiles\Sounds\unlock.wav" },
            { "PhotoScroll", @"C:\Programs\CommonFiles\Sounds\default.wav" },
            { "PingRing", @"C:\Programs\CommonFiles\Sounds\PingRing.wav" },
            { "Pip", @"C:\Programs\CommonFiles\Sounds\PIP.wav" },
            { "Reminder", @"C:\Programs\CommonFiles\Sounds\Nokia calendar.wma" },
            { "Reorder", @"C:\Programs\CommonFiles\Sounds\Reorder_Nokia.wav" },
            { "Ringback", @"C:\Programs\CommonFiles\Sounds\ringback.wav" },
            { "Ringout", @"C:\Programs\CommonFiles\Sounds\Callwait.wav" },
            { "RingPreview", @"" },
            { "RingTone", @"C:\Programs\CommonFiles\Sounds\2_VZW_ Cube.wma" },
            { "RingVoiceText", @"C:\Programs\CommonFiles\Sounds\Ring01.wma" },
            { "ScreenOff", @"C:\Programs\CommonFiles\Sounds\lock.wav" },
            { "ScreenOn", @"C:\Programs\CommonFiles\Sounds\unlock.wav" },
            { "Shutdown", @"C:\Programs\CommonFiles\Sounds\Remind.wma" },
            { "SMS", @"C:\Programs\CommonFiles\Sounds\Nokia message.wma" },
            { "SMSNudge", @"C:\Programs\CommonFiles\Sounds\Alert_nudge.wma" },
            { "StartButton", @"C:\Programs\CommonFiles\Sounds\default.wav" },
            { "SystemAsterisk", @"C:\Programs\CommonFiles\Sounds\default.wav" },
            { "SystemDefault", @"C:\Programs\CommonFiles\Sounds\default.wav" },
            { "SystemExclamation", @"C:\Programs\CommonFiles\Sounds\default.wav" },
            { "SystemHand", @"C:\Programs\CommonFiles\Sounds\default.wav" },
            { "SystemQuestion", @"C:\Programs\CommonFiles\Sounds\default.wav" },
            { "SystemStart", @"*none*" },
            { "Toolkit", @"C:\Programs\CommonFiles\Sounds\default.wav" },
            { "TransferComplete", @"C:\Programs\CommonFiles\Sounds\transfercomplete.wav" },
            { "VoiceMail", @"C:\Programs\CommonFiles\Sounds\Nokia email.wma" },
            { "VoicePrivacyDrop", @"C:\Programs\CommonFiles\Sounds\voiceprvcy.wav" },
            { "Warning", @"C:\Programs\CommonFiles\Sounds\Remind.wma" },
            { "WiFiConnected", @"C:\Programs\CommonFiles\Sounds\WiFiConnected.wav" },
            { "WiFiDisconnected", @"C:\Programs\CommonFiles\Sounds\WiFiDisconnected.wav" },
        };
#endif
    }
}
